log to stderr instead of stdout, cleanup db on bad exit

diff --git a/bin/import b/bin/import
--- a/bin/import
+++ b/bin/import
@@ -1,6 +1,32 @@
 #!/usr/bin/bash
 
 set -e
+trap 'catchExit $?' EXIT
+
+function log() {
+  echo "$@" >&2
+}
+
+function cleanup() {
+  log "Dropping Database ${DB_NAME}"
+  dropdb -f -U postgres ${DB_NAME}
+}
+
+function catchExit() {
+  case "$1" in
+    "0")
+      # Success!
+      ;;
+    "99")
+      log "exiting due to import validation failure"
+      ;;
+    *)
+      log "exiting due to unexpected error"
+      ;;
+  esac
+
+  cleanup
+}
 
 INPUT_DIR=$1
 RESULTS_DIR=$2
@@ -17,18 +43,18 @@ DB_NAME=`date +%Y%M%d%H%m%S`
 GUS_CONFIG=$WORKING_DIR/gus.config
 GEO_MAPPINGS=/usr/local/lib/xml/geoMappings.xml
 
-echo "WORKING Directory = ${WORKING_DIR}"
+log "WORKING Directory = ${WORKING_DIR}"
 
-echo "validate biom file and make metadata.json and data.tsv files"
+log "validate biom file and make metadata.json and data.tsv files"
 validateAndPreprocess $INPUT_DIR $WORKING_DIR
 
 cp $GUS_HOME/config/gus.config $GUS_CONFIG
 confReplace "${TEMPLATE_DB_NAME}" "$DB_NAME"
 
-echo "MAKING database ${DB_NAME}"
+log "MAKING database ${DB_NAME}"
 createdb -T $TEMPLATE_DB_NAME -U postgres $DB_NAME
 
-echo "Write Config ..."
+log "Write Config ..."
 writeNextflowConfig --workdir ${WORKING_DIR} \
   --gusConfigFile $GUS_CONFIG \
   --name $DB_NAME \
@@ -36,11 +62,9 @@ writeNextflowConfig --workdir ${WORKING_DIR} \
   --resultsDir ${RESULTS_DIR} \
   >${WORKING_DIR}/nextflow.config
 
-echo "Begin Loading ..."
+log "Begin Loading ..."
 nextflow -C ${WORKING_DIR}/nextflow.config \
   run $PROJECT_HOME/eda-nextflow/main.nf \
   -ansi-log false \
-  -entry loadBiomUserDataset
-
-echo "Dropping Database ${DB_NAME}"
-dropdb -f -U postgres ${DB_NAME}
+  -entry loadBiomUserDataset \
+  1>&2
